package domain.entity;

public enum AuditEvent {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    LOGIN_2FA_SUCCESS,
    LOGIN_2FA_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    QR_LOGIN_APPROVED,
    QR_LOGIN_DENIED,
    QR_LOGIN_EXPIRED,
    ACCOUNT_VERIFIED,
    ACCOUNT_CREATED,
    ACCOUNT_DELETED,
}
